name: Docker

on:
 workflow_dispatch:
 push:
    branches:
      - doodle_bear # default branch

jobs:
  publish:
    name: Publish to Dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"
      - name: Build Docker image
        run: |
          docker build -t luyanci/blc-bear:latest .
      - name: Login to DockerHub
        uses: docker/login-action@v3.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Push to DockerHub
        uses: docker/build-push-action@v5.3.0
        with:
          context: .
          push: true
          tags: luyanci/blc-bear:latest
    ToGhcr:
        name: Push to ghcr.io
        runs-on: ubuntu-latest
        env:
            image: ghcr.io/${{github.actor}}/blc-bear:latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
              with:
                submodules: recursive
            - name: Setup docker buildx
              uses: docker/setup-buildx-action@v3
            - name: Login to ghcr.io
              uses:  docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            - name: Build&Push
              uses: docker/build-push-action@v6
              with:
                context: .
                push: true
                tags: ${{env.image}}
                cache-from: type=registry,ref=${{env.image}}
                cache-to: type=inline 
